/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aula_10;

/**
 *
 * @author kelvi
 */
public class Principal extends javax.swing.JFrame {
    
    FuncionarioTM modelo;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        modelo = new FuncionarioTM();
        tbl_func.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_func = new javax.swing.JPanel();
        t_func_matricula = new javax.swing.JLabel();
        c_func_matricula = new javax.swing.JTextField();
        t_func_nome = new javax.swing.JLabel();
        c_func_nome = new javax.swing.JTextField();
        t_func_cpf = new javax.swing.JLabel();
        btn_func_cadastrar = new javax.swing.JButton();
        c_func_cpf = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_func = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painel_func.setBorder(javax.swing.BorderFactory.createTitledBorder("Funcionário"));

        t_func_matricula.setText("Matrícula:");

        c_func_matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_func_matriculaActionPerformed(evt);
            }
        });

        t_func_nome.setText("Nome:");

        t_func_cpf.setText("CPF:");

        btn_func_cadastrar.setText("Cadastrar");
        btn_func_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_func_cadastrarActionPerformed(evt);
            }
        });

        try {
            c_func_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout painel_funcLayout = new javax.swing.GroupLayout(painel_func);
        painel_func.setLayout(painel_funcLayout);
        painel_funcLayout.setHorizontalGroup(
            painel_funcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_funcLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(painel_funcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(t_func_cpf)
                    .addComponent(t_func_nome)
                    .addComponent(t_func_matricula))
                .addGap(18, 18, 18)
                .addGroup(painel_funcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(c_func_matricula)
                    .addComponent(c_func_nome)
                    .addComponent(c_func_cpf, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_funcLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_func_cadastrar)
                .addGap(140, 140, 140))
        );
        painel_funcLayout.setVerticalGroup(
            painel_funcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_funcLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(painel_funcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_func_matricula)
                    .addComponent(c_func_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_funcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_func_nome)
                    .addComponent(c_func_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_funcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_func_cpf)
                    .addComponent(c_func_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btn_func_cadastrar)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        tbl_func.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matrícula", "Nome", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_func);
        if (tbl_func.getColumnModel().getColumnCount() > 0) {
            tbl_func.getColumnModel().getColumn(0).setResizable(false);
            tbl_func.getColumnModel().getColumn(0).setPreferredWidth(100);
            tbl_func.getColumnModel().getColumn(1).setResizable(false);
            tbl_func.getColumnModel().getColumn(1).setPreferredWidth(200);
            tbl_func.getColumnModel().getColumn(2).setResizable(false);
            tbl_func.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painel_func, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel_func, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c_func_matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_func_matriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_func_matriculaActionPerformed

    private void btn_func_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_func_cadastrarActionPerformed
        Funcionario funcionario = new Funcionario();
        funcionario.setMatricula(c_func_matricula.getText());
        funcionario.setNome(c_func_nome.getText());
        funcionario.setCPF(c_func_cpf.getText());
        
        modelo.addFuncionario(funcionario);
        
    }//GEN-LAST:event_btn_func_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_func_cadastrar;
    private javax.swing.JFormattedTextField c_func_cpf;
    private javax.swing.JTextField c_func_matricula;
    private javax.swing.JTextField c_func_nome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painel_func;
    private javax.swing.JLabel t_func_cpf;
    private javax.swing.JLabel t_func_matricula;
    private javax.swing.JLabel t_func_nome;
    private javax.swing.JTable tbl_func;
    // End of variables declaration//GEN-END:variables
}
